name: Java Selenium Test Automation

on:
  push:
    branches:
      - main1
  pull_request:
    branches:
      - main1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 with distribution specified
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # Specify the JDK distribution (can be 'adoptopenjdk', 'zulu', etc.)

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: mvn clean install -DskipTests

      # Step 5: Set up Chrome and ChromeDriver
      - name: Set up Chrome and ChromeDriver
        run: |
          # Install Google Chrome
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable

          # Install the correct version of ChromeDriver based on the installed Chrome version
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | sed 's/\.[0-9]*$//') # Get Chrome version (e.g., 116)
          LATEST_CHROME_DRIVER=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget https://chromedriver.storage.googleapis.com/$LATEST_CHROME_DRIVER/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      # Step 6: Run Selenium Test Automation (TestNG)
      - name: Run Selenium Test Automation
        run: mvn test

      # Step 7: Upload Test Results (if you are using TestNG)
      - name: Upload TestNG Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/test-*.xml
