name: Java Selenium Test Automation

on:
  push:
    branches:
      - main1
  pull_request:
    branches:
      - main1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout Smoke-test Repository
        uses: actions/checkout@v3
        with:
          repository: Jitu722/Smoke-test  # Replace with the correct repository name
          token: ${{ secrets.GH_TOKEN }}  # Use the secret token for authentication
          path: Smoke-test-repo  # Directory where the Smoke-test repo will be checked out
          ref: main1  # Explicitly specify the branch name


      # Step 3: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 4: Cache Maven dependencies using the pom.xml in the Smoke-test repository
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('smoke-test-repo/**/pom.xml') }}  # Reference pom.xml from Smoke-test repo
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Install dependencies (from the main repository)
      - name: Install dependencies
        run: mvn clean install -DskipTests

      # Step 6: Run Selenium Test Automation (TestNG)
      - name: Run Selenium Test Automation
        run: mvn test

      # Step 7: Upload Test Results (specify the XML files)
      - name: Upload TestNG Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/*.xml  # Adjust according to the location of the results
